// Serve over https 
var fs = require('fs');
var http = require('http');
//const privateKey = fs.readFileSync('server.key');
//const certificate = fs.readFileSync('server.crt');

// generated by @ng-toolkit/universal
const port = process.env.PORT || 4200;

const server = require('./dist/server');

console.log(`Listening on: http://localhost:${port}`);
//LISTEN TO THE PORT WITH HTTP
http.createServer({
}, server.app).listen(port);