// Serve over https 
var fs = require('fs');
var https = require('https');
const privateKey = fs.readFileSync('server.key');
const certificate = fs.readFileSync('server.crt');

// generated by @ng-toolkit/universal
const port = process.env.PORT || 4200;

const server = require('./dist/server');

console.log(`Listening on: https://localhost:${port}`);
//LISTEN TO THE PORT WITH HTTPS
https.createServer({
    key: privateKey,
    cert: certificate
}, server.app).listen(port);